name: Fighting Design Github Actions

# 当 master 分支 push 代码的时候触发 workflow
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # 下载仓库代码 / 校验
      - name: Checkout
        # uses: actions/checkout@v3 # 这是github官方的一个action，用于clone该仓库的源码到工作流中，
        uses:
          actions/checkout@v3

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: npm install # 安装依赖
      - run: npm run build # 打包

      
      # 单元测试
      - name: test
        run: npm run test

      - name: build components
        run: npm run build

      # 打打包文档
      - name: build docs
        run: npm run build:docs

      # 向Codecov报告覆盖率
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
